# Generated by Django 3.0 on 2023-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20230411_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDBURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=32, unique=True)),
                ('url', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'pdb_url',
            },
        ),
    ]
