# Generated by Django 4.2.27 on 2026-03-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_diseaserecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseaserecommendation",
            name="cid",
            field=models.CharField(
                default="N/A", max_length=20, verbose_name="PubChem CID"
            ),
        ),
        migrations.AddField(
            model_name="diseaserecommendation",
            name="molecular_formula",
            field=models.CharField(
                default="N/A", max_length=100, verbose_name="分子式"
            ),
        ),
        migrations.AddField(
            model_name="diseaserecommendation",
            name="molecular_weight",
            field=models.CharField(default="N/A", max_length=20, verbose_name="分子量"),
        ),
        migrations.AddField(
            model_name="diseaserecommendation",
            name="smiles",
            field=models.TextField(default="N/A", verbose_name="SMILES字符串"),
        ),
        migrations.AlterModelTable(
            name="diseaserecommendation",
            table="web_diseaserecommendation",
        ),
    ]
