# Generated by Django 4.2.27 on 2026-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_pdburl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdburl",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
