# Generated by Django 4.2.27 on 2026-03-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_pdburl_id_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_type",
                    models.CharField(max_length=50, verbose_name="疾病类型"),
                ),
                (
                    "age_min",
                    models.IntegerField(blank=True, null=True, verbose_name="年龄下限"),
                ),
                (
                    "age_max",
                    models.IntegerField(blank=True, null=True, verbose_name="年龄上限"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("男", "男"), ("女", "女"), ("不限", "不限")],
                        default="不限",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "drug_name",
                    models.CharField(max_length=100, verbose_name="药物名称"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=10, verbose_name="优先级（越小越优先）"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="推荐理由")),
                (
                    "price_ref",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="参考价格"
                    ),
                ),
                (
                    "medicare_cn",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="医保覆盖"
                    ),
                ),
                (
                    "usage_summary",
                    models.TextField(blank=True, verbose_name="使用说明摘要"),
                ),
            ],
            options={
                "verbose_name": "疾病推荐药物",
                "verbose_name_plural": "疾病推荐药物",
            },
        ),
    ]
